# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/142FDA7ki-ks71qBRu2VCCPf2QwApA99c
"""

import numpy as np

lista_py = [1, 2, 3, 4, 5]
meu_array = np.array(lista_py)
print(meu_array.dtype)
print(meu_array.shape)
array_linear = np.linspace(0, 1, 5)
print(array_linear)

array0 = np.zeros((2, 2))
array1 = np.ones((2, 2))
print(array0)
print(array1)

#criando np array matriz
array_2d = np.array([
 [100, 200, 300, 400, 500],
 [10, 20, 30, 40, 50],
 [6, 7, 8, 9, 10]])
# Acessar o valor 200 do array_2d
elemento_200 = array_2d[0, 1]
print(elemento_200)
#slice
# Acessar a primeira linha inteira
primeira_linha = array_2d[0, :]
# Acessar a terceira coluna inteira
terceira_coluna = array_2d[:, 2]
teste = array_2d[2:, 1:4]
print(primeira_linha)
print(terceira_coluna)
print(teste)

#slice + step
segundo_array_2d = np.array([
 [0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14]])

linha_com_step = segundo_array_2d[1, ::2]
print(linha_com_step)

# aplicação com mais detalhes
slice_step = segundo_array_2d[1, 0:4:2]
print(slice_step)

#outros exemplos
terceiro_array_2d = np.array([
 [10, 11, 22, 30, 14],
 [15, 26, 37, 48, 59],
 [12, 18, 23, 13, 44],
 [23, 38, 43, 45, 78],
 [32, 51, 83, 23, 34],
 ])
slice_2d = terceiro_array_2d[1:3, ::2]
print(slice_2d)

#metodos no numpy
quarto_array_2d = np.array([
 [1, 2],
 [3, 4],
 [5, 6]])

# usando o sum
#para a soma das colunas axis=0
soma_colunas = quarto_array_2d.sum(axis=0)
print(soma_colunas)
#para a soma das linhas axis=1
soma_linhas = quarto_array_2d.sum(axis=1)
print(soma_linhas)
#somando todos os elementos
soma_todos = quarto_array_2d.sum()
print(soma_todos)

# usando o mean
media_colunas = quarto_array_2d.mean(axis=0)
print(media_colunas)
media_linhas = quarto_array_2d.mean(axis=1)
print(media_linhas)
media_total = quarto_array_2d.mean()
print(media_total)

#metodos no numpy
#usando o reshape

new_array = np.arange(10)
print(new_array)
array_2d = new_array.reshape(2, 5)
print(array_2d)

#colocando o -1 para o numpy calcular de maneira automatica
array_2d_auto = new_array.reshape(2, -1)
print(array_2d_auto)
array_2d_auto2 = new_array.reshape(-1, 5)
print(array_2d_auto2)

#retornar o array para 1d

array_1d = new_array.reshape(1, -1)
print(array_1d)

#concatenate

array1 = np.array([[1, 2, 3]])
array2 = np.array([[4, 5, 6]])

array3 = np.array([1, 2, 3])
array4 = np.array([4, 5, 6])

# Usa a função concatenate para unir os arrays
array_unido = np.concatenate((array3, array4))
# Usa a função concatenate para unir os arrays

array_unido2 = np.concatenate((array1, array2), axis=0)
print(array_unido)
print("//////////")
print(array_unido2)
print("//////////")

lista_2d = np.array([[1, 2, 3],
                     [5, 6, 7],
                     [9, 10, 11]])

segunda_lista_2d = np.array([[2, 4, 5],
                             [3, 1, 0]])

concat_linhas = np.concatenate((lista_2d, segunda_lista_2d), axis=0)

segunda_lista_arrumada = segunda_lista_2d.reshape(3, -1)

concat_colunas = np.concatenate((lista_2d, segunda_lista_arrumada), axis=1)

print("Array arrumado para concatenar as colunas: ")
print(segunda_lista_arrumada)
print("Lista concatenada: ")
print(concat_colunas)
print("//////////")
print(concat_linhas)

#Funções x Metodos

nova_lista_2d = np.array([[1, 2], [3, 4]])
outra_lista_2d = np.array([[5, 6]])

#usando o sum como função
resultado = np.sum(nova_lista_2d)
print(resultado)

#usando como metodo
resultado2 = nova_lista_2d.sum()
print(resultado2)