# -*- coding: utf-8 -*-
"""matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TdJQt1br1SlGQDwDuOOsq7H8bjSSf2CY
"""

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

#testes com polyfit e poly1d
x = np.array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])
y = np.array([0, 0.8, 0.9, 0.1, -0.8, -1.0, 0, 0.8, 0.9, 0.1, -0.8, -1.0])

# Perform linear fit
coefficients = np.polyfit(x, y, 1)
print("Linear Fit Coefficients:", coefficients)

# Create polynomial function
p = np.poly1d(coefficients)
print(p)

x = [1, 2, 3, 4, 5]
y = [2, 3, 4, 5, 6]
plt.scatter(x,y)
plt.title("Gráfico de Dispersão")
plt.xlabel("Eixo X")
plt.ylabel("Eixo Y")
plt.show()

horas_de_estudo = [1, 2, 3, 4, 5, 6, 7, 8]
pontuacao = [50, 55, 60, 65, 70, 75, 80, 85]
plt.scatter(horas_de_estudo, pontuacao, alpha=0.6, edgecolors='w', s=100)

z = np.polyfit(horas_de_estudo, pontuacao, 1)
p = np.poly1d(z)
print(z)
print(p(horas_de_estudo))
plt.plot(horas_de_estudo, p(horas_de_estudo), "r--")

plt.title("Relação entre Horas de Estudo e Pontuação", fontsize=16)
plt.xlabel("Horas de Estudo", fontsize=12)
plt.ylabel("Pontuação", fontsize=12)
plt.grid(True)
plt.show()

categorias = ['A', 'B', 'C', 'D']
valores = [3, 7, 2, 5]
plt.bar(categorias, valores)
plt.title("Gráfico de Barras")
plt.show()

filiais = ['Filial A', 'Filial B', 'Filial C', 'Filial D', 'Filial E']
receita = [200, 240, 150, 400, 220]

#Definindo as posições das barras no eixo X
posicoes = range(len(filiais))

plt.bar(posicoes, receita, color='skyblue', edgecolor='blue')

#Adicionado os nomes das filiais nas marcas no eixo X
plt.xticks(posicoes, filiais)

#Adicionando rótulos dos eixos e o titulo
plt.title("Receita Anual por filial", fontsize=16)
plt.xlabel("Filiais", fontsize=12)
plt.ylabel("Receita (em milhões de doláres)", fontsize=12)

plt.grid(True, axis='y', linestyle='--', alpha=0.7)

plt.show()

horas_de_trabalho = [2, 4, 6, 8]
salario_ganho = [1000, 2000, 3000, 4000]
plt.scatter(horas_de_trabalho, salario_ganho, alpha=0.6, edgecolors='w', s=100)

z = np.polyfit(horas_de_trabalho, salario_ganho, 1)
p = np.poly1d(z)

plt.plot(horas_de_trabalho, p(horas_de_trabalho), "r--")

plt.title("Relação entre Horas de Trabalho e Salário", fontsize=16)
plt.xlabel("Horas de Trabalho", fontsize=12)
plt.ylabel("Salário", fontsize=12)
plt.grid(True)
plt.show()

mes = ['Janeiro', 'Fevereiro', 'Março', 'Abril']
gastos = [2400, 2700, 3000, 3400]

posicoes = range(len(mes))

plt.bar(posicoes, gastos, color='skyblue', edgecolor='blue')

plt.xticks(posicoes, mes)

plt.title("Gastos mensais", fontsize=16)
plt.xlabel("Meses", fontsize=12)
plt.ylabel("Gasto", fontsize=12)

plt.grid(True, axis='y', linestyle='--', alpha=0.7)

plt.show()

#histograma
idades_funcionarios = [
    33, 58, 30, 35, 40, 45, 30, 51, 43, 35, 51, 33, 5, 33, 54, 35, 26, 33, 31, 44,
    21, 24, 55, 52, 44, 42, 55, 20, 24, 56, 24, 55, 22, 32, 25, 24, 26, 38, 30, 42,
    22, 25, 34, 62, 42, 40, 62, 24, 40, 61, 24, 60, 62, 23, 34, 45, 56, 33, 41, 44
]
plt.hist(idades_funcionarios, bins=[20, 30, 40, 50, 60, 70], color='dodgerblue', edgecolor='black')
plt.title("Distribuição de Idades dos Funcionários", fontsize=12)
plt.xlabel("Idade", fontsize=12)
plt.ylabel("Quantidade de Funcionários", fontsize=12)
#adicao no eixo x para as faixas etarias
plt.xticks([20, 30, 40, 50, 60])
plt.show()

# Gerar 24 dados aleatorios para simular os tempos de resposta médios a cada hora do dia
tempo_resposta = np.random.uniform(low=0.5, high=1.0, size=24)
#print(tempo_resposta, end="\n\n")
# Substituir aleatoriamente alguns valores por tempo de resposta > 1 segundo
tempo_resposta[np.random.choice(np.arange(24), size=5, replace=False)] = np.random.uniform(low=1.0, high=1.5, size=5)
#print(tempo_resposta)

plt.hist(tempo_resposta, bins=10, color='skyblue', edgecolor='blue')

#Adicionar títulos e rótulos
plt.title('Distribuição de Tempo de Resposta do Website')
plt.xlabel('Tempo de Resposta (segundos)')
plt.ylabel('Frequência')

#Desenhar uma vertical em x=1 para facilitar a visualização dos tempos > 1 segundo
plt.axvline(x=1, color='red', linestyle='--', label='1 segundo')

plt.legend()

plt.show()

# Gerar dados aleatórios (ex: notas de alunos)
dados = np.random.randn(100) * 10 + 70 # Média 70, desvio padrão 10
print(dados)
# Histograma com 10 bins
plt.hist(dados, bins=10)
plt.title('Histograma com 10 Bins')
plt.xlabel('Valores')
plt.ylabel('Frequência')
plt.show()

tempo_download = np.random.uniform(low=5, high=15, size=20)
#(tempo_download)
tempo_download[np.random.choice(np.arange(20), size=6, replace=False)] = np.random.uniform(low=10, high=30, size=6)
#print(tempo_download)

plt.hist(tempo_download, bins=10, color='skyblue', edgecolor='blue')

plt.title('Distribuição de Tempo de Resposta do Website')
plt.xlabel('Tempo de Resposta (segundos)')
plt.ylabel('Frequência')

plt.axvline(x=15, color='red', linestyle='--', label='1 segundo')

plt.legend()

plt.show()

#grafico de linha
x = range(10)
y = [x**2 for x in range(10)]
plt.plot(x, y)
plt.title("Gráfico de Linha")
plt.show()

#pandas com matplotlib
dados_finaceiros = {'Ano': [2015, 2016, 2017, 2018], 'Lucro': [15, 18, 20, 22]}
df = pd.DataFrame(dados_finaceiros)
df.plot(x='Ano', y='Lucro', kind='line')
plt.show()

dados_climaticos = pd.DataFrame({'Temperature': [22, 24, 19, 24]})
dados_climaticos.hist(bins=3)
plt.show()

#POO no matplotlib
#dados para os gráficos
meses = np.array(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'])
vendas = np.array([20, 35, 30, 35, 27, 35])
satisfacao_cliente = np.array([70, 82, 73, 65, 90, 83])

#Criacao de um objeto Figure e dois objetos Axes
fig, ax1 = plt.subplots()

#Plotando as vendas com um gráfico de barras no primeiro axes
ax1.bar(meses, vendas, color='g', label='Vendas')
ax1.set_xlabel('Mês')
ax1.set_ylabel('Vendas', color='g')
ax1.tick_params('y', colors='g')

#Criando um segundo Axes que compartilha o mesmo eixo x
ax2 = ax1.twinx()

#Plotando a satisfação do cliente com um gráfic de linha no segundo Axes
ax2.plot(meses, satisfacao_cliente, color='b', label='Satisfação do Cliente')
ax2.set_ylabel('Satisfação do cliente (%)', color='b')
ax2.tick_params('y', colors='b')

#Adicionar título e mostrar a legenda
fig.suptitle('Vendas e Satisfação do Cliente por Mês')
ax1.legend(loc='upper left')
ax2.legend(loc='upper right')

#Mostrar o gráfico
plt.show()

grafico_1_x = [x * 2 for x in range(10)]
grafico_1_y = [x ** 2 for x in range(10)]

grafico_2_x = np.round(np.random.uniform(low=50, high=200, size=10))
grafico_2_y = np.round(np.random.uniform(low=10, high=100, size=10))

grafico_3_x = [x ** 3 for x in range(10)]
grafico_3_y = [x ** 4 for x in range(10)]

grafico_4_x = np.round(np.random.uniform(low=50, high=200, size=10))
grafico_4_y = np.round(np.random.uniform(low=10, high=100, size=10))

fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(12, 6))

#grafico 1
ax1.plot(grafico_1_x, grafico_1_y, color="blue")
ax1.set_title("Gráfico 1")
ax1.set_xlabel("Eixo X")
ax1.set_ylabel("Eixo Y")
#grafico 2
ax2.scatter(grafico_2_x, grafico_2_y, color="yellow")
ax2.set_title("Gráfico 2")
ax2.set_xlabel("Eixo X")
ax2.set_ylabel("Eixo Y")
#grafico 3
ax3.hist(grafico_3_x, bins=10, color="green")
ax3.set_title("Gráfico 3")
ax3.set_xlabel("Eixo X")
ax3.set_ylabel("Eixo Y")
#grafico 4
ax4.bar(grafico_4_x, grafico_4_y, color="red")
ax4.set_title("Gráfico 4")
ax4.set_xlabel("Eixo X")
ax4.set_ylabel("Eixo Y")

#Ajustar o layout para evitar sobreposição
fig.tight_layout()
plt.show()

#Dados para o gráfico
a = [1, 2, 3, 4]
b = [7, 3, 1, 4]
c = [4, 2, 3, 5]

#Criar uma figura e um conjunto de subplots com linha e 2 colunas
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))

#Gráfico de dispersão no primeiro subplot (Axes)
ax1.scatter(a, b, color='blue')
ax1.set_title('Gráfico de Dispersão')
ax1.set_xlabel('Eixo X')
ax1.set_ylabel('Eixo Y')

#Gráfico de linha no segundo subplot (Axes)

ax2.plot(a, c, color='red')
ax2.set_title('Gráfico de Linha')
ax2.set_xlabel('Eixo X')
ax2.set_ylabel('Eixo Y')

#Ajustar o layout para evitar sobreposição
fig.tight_layout()
plt.show()

#mais exemplos
cloud_providers = ['AWS', 'Azure', 'Google Cloud', 'IBM', 'Alibaba']
receita = [35.03, 15.16, 8.92, 6.01, 5.65]  # Receita em bilhões de dólares
crescimento = [29, 47, 52, 11, 62]  # Crescimento percentual ano a ano
# Configuração do tamanho da figura para melhor visibilidade
plt.figure(figsize=(10, 6))

# Criação do gráfico de dispersão
for i in range(len(cloud_providers)):
    plt.scatter(receita[i], crescimento[i], label=cloud_providers[i], s=100, alpha=0.5)

# Títulos e rótulos dos eixos
plt.title('Posicionamento dos Principais Cloud Providers Mundiais', fontsize=16)
plt.xlabel('Receita Anual (em bilhões de dólares)', fontsize=12)
plt.ylabel('Crescimento Ano a Ano (%)', fontsize=12)

# Adição de uma grade para melhor leitura dos dados
plt.grid(True)

# Inclusão de uma legenda para identificar cada ponto
plt.legend()

# Exibição do gráfico
plt.show()

trimestres = [1, 2, 3, 4]
produto_a = [60, 65, 72, 80]
produto_b = [55, 68, 75, 85]
produto_c = [50, 60, 80, 90]
plt.plot(trimestres, produto_a, color='blue', linestyle='-', marker='s', linewidth=2)
plt.plot(trimestres, produto_b, color='red', linestyle='--', marker='^', linewidth=2)
plt.plot(trimestres, produto_c, color='purple', linestyle='-.', marker='d', linewidth=2)

plt.title("Comparação do Crescimento de Três Produtos", fontsize=16, color='navy')
plt.xlabel("Trimestres", fontsize=14)
plt.ylabel("Vendas (em unidades)", fontsize=14)
plt.legend(['Produto A', 'Produto B', 'Produto C'])
plt.grid(True)
plt.show()

trimestres = [x ** 3 * 2 / 2 for x in range(10)]
trimestres[0] = 0.5
produto_a = [x ** 2 for x in range(10)]
produto_a[0] = 0.6
produto_b = [x ** 3 for x in range(10)]
produto_b[0] = 0.7
produto_c = [x ** 4 for x in range(10)]
produto_c[0] = 0.8
plt.plot(trimestres, produto_a, color="purple", linestyle=":", marker='^', linewidth=2)
plt.plot(trimestres, produto_c, color="red", linestyle="--", marker='d', linewidth=2)
plt.plot(trimestres, produto_b, color="blue", linestyle="-.", marker='s', linewidth=2)

plt.title("Comparação do Crescimento de Três Produtos", fontsize=16, color='navy')
plt.xlabel("Trimestres", fontsize=14)
plt.ylabel("Vendas (em unidades)", fontsize=14)
plt.legend(['Produto A', 'Produto B', 'Produto C'])
plt.grid(True)
plt.show()