# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xiu9rgl_IwAu5TmiwNMBthVp4hpUR6NN
"""

#inicio do curso

import matplotlib.pyplot as plt
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]
plt.plot(x, y)
plt.xlabel('Eixo X')
plt.ylabel('Eixo Y')
plt.title('Exemplo de Gráfico')
plt.show()

#pandas
import pandas as pd
import numpy as np

#series com pandas
idades = [10, 20, 33]
serie_idade = pd.Series(idades)
print(serie_idade, end='\n\n')

serie_com_nomes = pd.Series(idades, index=['João', 'Maria', 'Pedro'])
print(serie_com_nomes)

index = "João"
print(f"{index} idade: ", serie_com_nomes[index])

serie_mista = pd.Series(data=[100, 'Py', 3.14])
print(serie_mista)

serie_dict = pd.Series({'a': 1, 'b': 2, 'c': 3})
print(serie_dict)
print("b = ", serie_dict.b)

#operações matemáticas com pandas

serie = pd.Series([25, 450, 600], index=['a', 'b', 'c'])
serie_dobro = serie * 2
print(serie_dobro, end='\n\n')

media = serie.mean()
print(media, end='\n\n')

mediana = serie.median()
print(mediana, end='\n\n')

desvio_padrao = serie.std()
print(desvio_padrao, end='\n\n')

# Aplicando logaritmo natural a cada valor
lob_valores = np.log(serie)
print(lob_valores, end='\n\n')

valores_acima_media = serie > serie.mean()
print(valores_acima_media, end='\n\n')

valores_selecionados = serie[serie > 50]
print(valores_selecionados)

temperaturas = pd.Series([25.3, np.nan, 27.5, 24.4, np.nan, 26.8, 22.8, 19.8, np.nan, 26.9, 27.8, 29.8],
                         index=['janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro'])
print(temperaturas, end='\n\n')
nulos = temperaturas.isnull()
print(nulos, end='\n\n')

#para preencher os valores nulos
temperatura_preenchida = temperaturas.fillna(temperaturas.mean())
print(temperatura_preenchida, end='\n\n')

#para remover os valores nulos
temperatura_sem_nulos = temperaturas.dropna()
print(temperatura_sem_nulos, end='\n\n')

# Aplicando uma função customizada a cada elemento da série
serie_customizada = serie.apply(lambda x: x**2 if x > 50 else x + 10)
print(serie_customizada, end='\n\n')

serie1 = pd.Series([25, 450, 600], index=['a', 'b', 'c'])
serie2 = pd.Series([50, 40, 60], index=['a', 'b', 'c'])

# Somando valores de duas séries diferentes
soma_series = serie1 + serie2

# Concatenando séries
serie_concatenada = pd.concat([serie1, serie2])
print(soma_series)
print("#######")
print(serie_concatenada)

#dataframes

#criando dataframe simples
dataframe = pd.DataFrame(data=[[1, 'John'], [2, 'Jane']], columns=['ID', 'Nome'])
print(dataframe, end="\n\n")

dataframe2 = pd.DataFrame(data=[[1, 'John'], [2, 'Jane']], columns=['ID', 'Nome'], index=['linha1', 'linha2'])
print(dataframe2, end="\n\n")

# pegando dados em posições especificas
# Acessar valor específico
print(dataframe2.loc['linha1', 'ID'], end="\n\n")      # 1
print(dataframe2.loc['linha2', 'Nome'], end="\n\n")    # 'Jane'
# Acessar linha inteira
print(dataframe2.loc['linha1'], end="\n\n")

# Acessar por posição numérica
print(dataframe2.iloc[0, 1], end="\n\n")
print(dataframe2.iloc[1, 1], end="\n\n")

# Acessar linha inteira
print(dataframe2.iloc[0])

# DataFrame a partir de um dicionário
dados = {
    'ID': [1, 2, 3],
    'Nome': ['John', 'Jane', "Jim"],
    'Idade': [22, 33, 44]
}
df_dicionario = pd.DataFrame(dados)
print(df_dicionario, end="\n\n")

#####

df_indices = pd.DataFrame(data=dados, index=['Linha1', 'Linha2', 'Linha3'])
print(df_indices, end="\n\n")

# print(df_dicionario.iloc[0, 2])
# print(df_dicionario.loc[0, 'Nome'])

#adicionando coluna
df_indices['Salario'] = [5000, 6000, 7000]
print(df_indices)

# DataFrame complexo com vários tipos de dados
df_complexo = pd.DataFrame({
    'A': pd.Series([1, 2, 3], index=['primeiro', 'segundo', 'terceiro']),
    'B': np.linspace(0, np.pi, 3),
    'C': pd.date_range(start='20210101', periods=3, freq='D')
})
print(df_complexo)
print("/////////////")
objeto = {
    'Primeiro': pd.Series([10, 20, 30], index=['a', 'b', 'c']),
    'Segundo': np.linspace(0, 10, 3),
    'Terceiro': pd.date_range(start='20250101', periods=3, freq='ME')
}
df_new = pd.DataFrame(objeto)
print(df_new)

#lendo arquivos
classData = pd.read_csv('pandas-sample-data.csv')
print(classData)
print("/////////////")
#Primeiras 5 linhas
print(classData.head())
print("/////////////")
#Ultimas 5 linhas
print(classData.tail())
print("/////////////")
#Vendo os tipos de dados
print(classData.dtypes)
print("/////////////")
#Informações sobre o dataframe
print(classData.info())
print("/////////////")
#Descrição estatística do dataframe
print(classData.describe())
print(classData.describe(include=[object]))
print("/////////////")
#Quantidade de instrutores únicos
print(classData['Instrutor'].value_counts())
print("/////////////")
#Contagem AE únicos
print(classData['AE'].value_counts())
print("/////////////")

classData = pd.read_csv('pandas-sample-data.csv')

#seleção de colunas específicas
df_avaliacao_inscritos = classData[['Avaliacao', 'Inscritos']]
print(df_avaliacao_inscritos, end='\n\n')

#Filtragem de linhas baseada em uma condição
df_filtrado = classData[classData['Avaliacao'] >= 4.5]
print(df_filtrado, end='\n\n')

#Ordenando pela avaliação de forma descendente
df_ordenado = classData.sort_values(by='Avaliacao', ascending=False)
print(df_ordenado, end='\n\n')

#agrupando por instrutor e obtendo a media de inscritos
df_grupo_inscritos = classData.groupby('Instrutor')['Inscritos'].mean()
print(df_grupo_inscritos, end='\n\n')

#identificando dados faltantes
print(classData.isnull().sum(), end='\n\n')

#Preenchendo dados faltantes
df_preenchido = classData.fillna({'Avaliacao': classData['Avaliacao'].mean()})
print(df_preenchido, end='\n\n')

#Plotando a distribuição das avaliações
classData['Avaliacao'].plot(kind='hist')

dataframe_teste = pd.DataFrame([
    {"nome": 'vitoria', "idade": 22},
    {"nome": 'joao', "idade": 23},
    {"nome": 'pedro', "idade": 24}
])

print("pegando posições com loc")
for i in range(len(dataframe_teste)):
  print(dataframe_teste.loc[i, "nome"], dataframe_teste.loc[i, "idade"])
print("pegando posições com iloc")
for i in range(len(dataframe_teste)):
  print(dataframe_teste.iloc[i, 0], dataframe_teste.iloc[i, 1])

classData = pd.read_csv('pandas-sample-data.csv')
print(classData)

classData.columns = ['Codigo_Curso', 'Nome_Instrutor', 'Assistente_Ensino', 'Total_Inscritos', 'Media_Avaliacao']
print(classData)

classData.rename(columns={
    'ID_Curso': 'Codigo_Curso',
    'Instrutor': 'Nome_Instrutor',
    'AE': 'Assistencia_Ensino',
    'Inscritos': 'Total_Inscritos',
    'Avaliacao': 'Media_Avaliacao'
}, inplace=True)

print(classData)

classData.rename(columns=lambda x: x.lower().replace(" ", "_"), inplace=True)
print(classData)
classData.rename(index=lambda i: 'Linha_' + str(i), inplace=True)
print(classData)

classData = pd.read_csv('pandas-sample-data.csv')

inscritos = classData['Inscritos']
print(inscritos, end="\n\n")
avaliacao = classData.Avaliacao
print(avaliacao)

df_selecionado = classData[['Instrutor', 'AE', 'Avaliacao']]
print(df_selecionado, end='\n\n')

array_booleano = classData['Avaliacao'] > 4.7
print(array_booleano, end='\n\n')

melhores_cursos = classData[array_booleano]
print(melhores_cursos, end='\n\n')

instrutores_melhores_cursos = classData.loc[classData['Avaliacao'] > 4.7, 'Instrutor']
print(instrutores_melhores_cursos, end='\n\n')

#Cursos com Avaliacao acima de 4.7 e menos de 50 inscritos
condicao = (classData['Avaliacao'] > 4.7) & (classData['Inscritos'] < 50)
print(condicao, end="\n\n")
cursos_filtrados = classData[condicao]
print(cursos_filtrados, end='\n\n')

#selecionando os primeiros 5 curso e apenas as colunas de 'Instrutor' e 'Avaliação'
primeiros_cursos = classData.iloc[0:5, [1, 4]]
print(primeiros_cursos)

classData.loc[(classData['ID_Curso'] == 'MT102') & (classData['Instrutor'] == 'Luiz Costa'), 'Inscritos'] = 59
print(classData)

df = pd.read_csv('pandas-sample-data.csv')

media_inscritos = df['Inscritos'].mean()
#preenchendo os valores nulos da Inscritos com a media de Inscritos
df['Inscritos'].fillna(media_inscritos, inplace=True)
print(df, end="\n\n")
#preenchendo os valores nulos da Avaliacao com a media de Avaliacao
media_avaliacao = df['Avaliacao'].mean()
df['Avaliacao'].fillna(media_avaliacao, inplace=True)
print(df)

df.loc[df['Inscritos'] < 50, 'Avaliacao'] *= 1.1
#convertendo coluna float para int. Para isso funcionar nao pode ter valores nulos
df['Inscritos'] = df['Inscritos'].astype(int)
print(df)

#criando mais uma coluna com a relacao entre inscritos e avaliacao
df['Relacao_Inscritos_Avaliacao'] = df['Inscritos'] / df['Avaliacao']
print(df)

#removendo colunas
df.drop(columns=['AE'], inplace=True)
print(df)

print(df, end="\n\n")
df.reset_index(drop=True, inplace=True)
print(df, end="\n\n")

df.rename(columns={'Instrutor': 'Prof', 'Inscritos': 'Alunos', 'Avaliacao': 'Nota'}, inplace=True)
print(df)

classData = pd.read_csv('pandas-sample-data.csv')
cursos_selecionados = classData.loc[(classData['ID_Curso'].str.contains('FI')) & (classData['Inscritos'] > 45)]
print(cursos_selecionados, end="\n\n")

valores_unicos = classData['Instrutor'].unique()
print(valores_unicos, end="\n\n")

media_por_curso = classData.groupby('ID_Curso')['Avaliacao'].mean()
print(media_por_curso, end="\n\n")

#primeira forma de fazer
df = pd.read_csv('pandas-sample-data.csv')
dataframe = pd.DataFrame([
    {"idade": 22},
    {"idade": 23},
    {"idade": 24},
    {"idade": 24},
    {"idade": 25},
    {"idade": 25},
    {"idade": 26},
    {"idade": 26},
    {"idade": 26},
    {"idade": 27},
    {"idade": 27},
    {"idade": 27},
    {"idade": 27},
    {"idade": 28},
    {"idade": 28},
    {"idade": 28},
    {"idade": 28},
    {"idade": 28},
    {"idade": 29},
    {"idade": 29}
])
dataframe.to_csv('dataframe.csv')
df_dicionario = pd.read_csv('dataframe.csv')
df_dicionario.drop(columns=['Unnamed: 0'], inplace=True)
# Adicionar uma coluna de índice para fazer o merge
df_dicionario['id'] = range(len(df_dicionario))

df['id'] = range(len(df))

# Fazer o merge pelo índice
df_detalhado = df.merge(df_dicionario, on='id')

df_detalhado.drop(columns=['id'], inplace=True)
print(df_detalhado)

#segunda forma de fazer
df = pd.read_csv('pandas-sample-data.csv')
dataframe = pd.DataFrame([
    {"idade": 22},
    {"idade": 23},
    {"idade": 24},
    {"idade": 24},
    {"idade": 25},
    {"idade": 25},
    {"idade": 26},
    {"idade": 26},
    {"idade": 26},
    {"idade": 27},
    {"idade": 27},
    {"idade": 27},
    {"idade": 27},
    {"idade": 28},
    {"idade": 28},
    {"idade": 28},
    {"idade": 28},
    {"idade": 28},
    {"idade": 29},
    {"idade": 29}
])
dataframe.to_csv('dataframe.csv')
df_dicionario = pd.read_csv('dataframe.csv')
df_dicionario.drop(columns=['Unnamed: 0'], inplace=True)
# Adicionar uma coluna de índice para fazer o merge
df_com_id = df.reset_index().rename(columns={'index': 'id'})
df_dicionario_com_id = df_dicionario.reset_index().rename(columns={'index': 'id'})

df_detalhado = df_com_id.merge(df_dicionario_com_id, on='id')
df_detalhado = df_detalhado.drop(columns=['id'])
print(df_detalhado)

tabela_dinamica = df.pivot_table(values='Inscritos', index='ID_Curso', columns='Instrutor', aggfunc='sum')
print(tabela_dinamica)