# -*- coding: utf-8 -*-
"""regression_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G6xQRuoPmIORRN7i7enj2T53x2d7KyQo
"""

from sklearn.linear_model import Ridge, LinearRegression
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score
import seaborn as sns
from sklearn.decomposition import PCA
import pandas as pd
from sklearn.svm import SVC

#Carregar o conjunto de dados
diabetes = load_diabetes()

#Seperar variavel X e Y
x = diabetes.data[:, 2]
y = diabetes.target

#Dividindo os dados em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

#Criando o modelo de regressão linear
model = LinearRegression()

#Treinando o modelo com os dados de treinamento
model.fit(X_train.reshape(-1, 1), y_train)

#Fazendo previsões com os dados de testes
y_pred = model.predict(X_test.reshape(-1, 1))

# Plotando o gráfico de dispersão dos dados de teste
plt.scatter(X_test, y_test, color='blue', label='Dados de Teste')

# Plotando a linha de regressão
plt.plot(X_test, y_pred, color='red', linewidth=2, label='Linha de Regressão')

#Adicionando rotulos e titulo ao grafico
plt.xlabel('Característica')
plt.ylabel('Progressão da doença')
plt.title('Regressão linear - Diabetes')
plt.legend()

#Exibir
plt.show()

tempo = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).reshape(-1, 1)
velocidade = np.array([10, 20, 30, 40, 50, 60, 65, 70, 70, 70])

#Usamos a polinomial pois os dados de velocidade nao crescem em uma constante linear

poly = PolynomialFeatures(degree=2)
tempo_poly = poly.fit_transform(tempo)

model = LinearRegression()

model.fit(tempo_poly, velocidade)

plt.scatter(tempo, velocidade, color='blue', label='Dados de Teste')
plt.plot(tempo, model.predict(tempo_poly), color='red', linewidth=2, label='Linha de Regressão')
plt.title("Regressão Polinomial")
plt.xlabel('Tempo')
plt.ylabel('Velocidade')
plt.show()

#Carregar o conjunto de dados
diabetes = load_diabetes()

#Seperar variavel X e Y
x = diabetes.data[:, np.newaxis, 2] # com o np.newaxis transforma em uma array 2d
y = diabetes.target

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

model = LinearRegression()

model.fit(X_train_poly, y_train)

y_pred = model.predict(X_test_poly)

mse = mean_squared_error(y_test, y_pred)

print("MSE: ", mse)

plt.scatter(X_test, y_test, color='blue')
plt.scatter(X_test, y_pred, color='red')

plt.title('Regressão Polinomial')
plt.xlabel('Medição de índice de massa corporal')
plt.ylabel('Progressão da doença')
plt.show()

#Carregar o conjunto de dados
diabetes = load_diabetes()

#Seperar variavel X e Y
x = diabetes.data[:, np.newaxis, 2] # com o np.newaxis transforma em uma array 2d
y = diabetes.target

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

#Criação do pipeline
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("poly_features", PolynomialFeatures(degree=2)),
    ("regressoor", LinearRegression())
])


pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_test)

mse = mean_squared_error(y_test, y_pred)

print("MSE: ", mse)

plt.scatter(X_test, y_test, color='blue', label='Dados de Teste')
X_plot = np.linspace(X_test.min(), X_test.max(), 100)[:, np.newaxis]
y_plot = pipeline.predict(X_plot)
plt.plot(X_plot, y_plot, color='red', linewidth=2, label='Curva de Regressão Polinomial')

plt.title('Regressão Polinomial')
plt.xlabel('Caracteristica')
plt.ylabel('Regressão Polinomial com Pipeline - Dados de Diabetes')
plt.legend()
plt.show()

#Carregar o conjunto de dados
diabetes = load_diabetes()

#Seperar variavel X e Y
x = diabetes.data[:, np.newaxis, 2] # com o np.newaxis transforma em uma array 2d
y = diabetes.target

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = make_pipeline(PolynomialFeatures(degree=2), LinearRegression())

#validação cruzada
scores = cross_val_score(model, X_train, y_train, cv=5)

print("Scores: ", scores)
print("Score média: ", scores.mean())

data = [
    ['A', 8, 'Sim', 'Baixo', 'Boa'],
    ['B', 6, 'Não', 'Alto', 'Ruim'],
    ['C', 7, 'Sim', 'Moderado', 'Regular'],
    ['D', 5, 'Não', 'Alto', 'Ruim'],
    ['E', 9, 'Sim', 'Baixo', 'Boa'],
    ['F', 6, 'Não', 'Moderado', 'Regular'],
    ['G', 7, 'Sim', 'Baixo', 'Regular'],
    ['H', 8, 'Não', 'Baixo', 'Boa'],
    ['I', 5, 'Sim', 'Alto', 'Ruim'],
    ['J', 7, 'Não', 'Moderado', 'Regular']
]

#para x vai pegar as linhas do array do indice um ate o penultimo
#para y vai pegar a ultima linha. Faz isso utilizando o -1
x = [row[1:-1] for row in data]
y = [row[-1] for row in data]

X_enconded = []
for row in x:
  hours = int(row[0])
  exercise = 1 if row[1] == 'Sim' else 0
  stress = {'Baixo': 0, 'Moderado': 1, 'Alto': 2}[row[2]]
  X_enconded.append([hours, exercise, stress])

clf = DecisionTreeClassifier()
clf.fit(X_enconded, y)

plt.figure(figsize=(12, 12))
plot_tree(clf, filled=True, feature_names=['Horas de Sono', 'Exercicio Físico', 'Estresse'], class_names=['Boa', 'Regular', 'Ruim'])
plt.show()

new_data = [[7, 'sim', 'Baixo'], [6, 'Não', 'Alto'], [8, 'Sim', 'Moderado']]
new_data_encoded = []

for row in new_data:
  hours = int(row[0])
  exercise = 1 if row[1] == "sim" else 0
  stress = {'Baixo': 0, 'Moderado': 1, 'Alto': 2}[row[2]]
  new_data_encoded.append([hours, exercise, stress])

predictions = clf.predict(new_data_encoded)
print("Predições: ", predictions)

data = [
    ['A', 8, 'Sim', 'Baixo', 'Boa'],
    ['B', 6, 'Não', 'Alto', 'Ruim'],
    ['C', 7, 'Sim', 'Moderado', 'Regular'],
    ['D', 5, 'Não', 'Alto', 'Ruim'],
    ['E', 9, 'Sim', 'Baixo', 'Boa'],
    ['F', 6, 'Não', 'Moderado', 'Regular'],
    ['G', 7, 'Sim', 'Baixo', 'Regular'],
    ['H', 8, 'Não', 'Baixo', 'Boa'],
    ['I', 5, 'Sim', 'Alto', 'Ruim'],
    ['J', 7, 'Não', 'Moderado', 'Regular']
]

#para x vai pegar as linhas do array do indice um ate o penultimo
#para y vai pegar a ultima linha. Faz isso utilizando o -1
x = [row[1:-1] for row in data]
y = [row[-1] for row in data]

X_enconded = []
for row in x:
  hours = int(row[0])
  exercise = 1 if row[1] == 'Sim' else 0
  stress = {'Baixo': 0, 'Moderado': 1, 'Alto': 2}[row[2]]
  X_enconded.append([hours, exercise, stress])

clf = RandomForestClassifier(n_estimators=100)

clf.fit(X_enconded, y)
#escolhendo uma arvore especifica para mostrar
estimator = clf.estimators_[0]

plt.figure(figsize=(12, 12))
plot_tree(estimator, filled=True, feature_names=['Horas de Sono', 'Exercicio Físico', 'Estresse'], class_names=['Boa', 'Regular', 'Ruim'])
plt.show()

new_data = [[7, 'sim', 'Baixo'], [6, 'Não', 'Alto'], [8, 'Sim', 'Moderado']]
new_data_encoded = []

for row in new_data:
  hours = int(row[0])
  exercise = 1 if row[1] == "sim" else 0
  stress = {'Baixo': 0, 'Moderado': 1, 'Alto': 2}[row[2]]
  new_data_encoded.append([hours, exercise, stress])

predictions = clf.predict(new_data_encoded)
print("Predições: ", predictions)

from sklearn.datasets import load_iris

# Carregando o conjunto de dados Iris
iris = load_iris()
X = iris.data
y = iris.target

# Dividindo os dados em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Criando e treinando a Decision Tree
dt_clf = DecisionTreeClassifier()
dt_clf.fit(X_train, y_train)

# Criando e treinando a Random Forest
rf_clf = RandomForestClassifier(n_estimators=100)
rf_clf.fit(X_train, y_train)

# Fazendo previsões nos dados de teste
dt_predictions = dt_clf.predict(X_test)
rf_predictions = rf_clf.predict(X_test)

# Calculando a acurácia das previsões
dt_accuracy = accuracy_score(y_test, dt_predictions)
rf_accuracy = accuracy_score(y_test, rf_predictions)

print("Acurácia da Decision Tree:", dt_accuracy)
print("Acurácia da Random Forest:", rf_accuracy)

# Plotando a árvore de decisão
plt.figure(figsize=(12, 8))
plot_tree(dt_clf, filled=True, feature_names=iris.feature_names, class_names=iris.target_names)
plt.show()

from sklearn.datasets import make_circles
from sklearn.svm import SVC


# Gerando dados sintéticos
X, y = make_circles(n_samples=400, factor=0.3, noise=0.1)

# Dividindo os dados em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Visualizando os dados
plt.figure(figsize=(8, 6))
plt.scatter(X[:, 0], X[:, 1], c=y, cmap='viridis', edgecolors='k')
plt.title("Dados Não Separáveis Linearmente")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.show()

print("\n\n")
# Treinando o modelo SVM com kernel RBF
model = SVC(kernel='rbf', gamma='auto')
model.fit(X_train, y_train)

# Visualizando a fronteira de decisão
plt.figure(figsize=(8, 6))
plt.scatter(X[:, 0], X[:, 1], c=y, cmap='viridis', edgecolors='k')

# Criando uma grade para plotar as fronteiras de decisão
xx, yy = np.meshgrid(np.linspace(-1.5, 1.5, 500),
                     np.linspace(-1.5, 1.5, 500))

"""
xx e yy são matrizes 2D (500x500) criadas por np.meshgrid()
xx.ravel() transforma a matriz 500x500 em um array 1D com 250.000 elementos
yy.ravel() faz o mesmo
np.c_[] concatena esses dois arrays 1D lado a lado, criando uma matriz com 250.000 linhas e 2 colunas
O model.predict() espera uma matriz 2D onde:
Cada linha é uma amostra
Cada coluna é uma feature
"""

Z = model.predict(np.c_[xx.ravel(), yy.ravel()])

Z = Z.reshape(xx.shape)

plt.contourf(xx, yy, Z, alpha=0.75, cmap='viridis')
plt.title("Fronteira de Decisão com SVM e Kernel RBF")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.show()

from sklearn.datasets import make_blobs
import matplotlib.pyplot as plt
import numpy as np

# Gerando dados sintéticos
X, y = make_blobs(n_samples=100, centers=3, random_state=42, cluster_std=1.5)

# Visualizando os dados
plt.figure(figsize=(10, 6))
plt.scatter(X[:, 0], X[:, 1], c=y, cmap='viridis', edgecolor='k', s=100)
plt.title("Conjunto de Dados Sintético")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.show()

from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier, OneVsOneClassifier
from sklearn.preprocessing import StandardScaler

# Normalizando os dados
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Treinando os modelos
model_ovr = OneVsRestClassifier(SVC(kernel='linear', probability=True)).fit(X_scaled, y)
model_ovo = OneVsOneClassifier(SVC(kernel='linear', probability=True)).fit(X_scaled, y)
def plot_decision_boundaries(X, y, model, title):
    # Definindo valores mínimos e máximos e criando uma grade
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.1),
                         np.arange(y_min, y_max, 0.1))

    # Previsão de cada ponto na grade
    Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)

    # Plotando o resultado
    plt.contourf(xx, yy, Z, alpha=0.4, cmap='viridis')
    plt.scatter(X[:, 0], X[:, 1], c=y, cmap='viridis', edgecolor='k', s=100)
    plt.title(title)
    plt.xlabel("Feature 1")
    plt.ylabel("Feature 2")
    plt.show()

# Visualizando as fronteiras de decisão
plot_decision_boundaries(X_scaled, y, model_ovr, "Fronteiras de Decisão OvR")
plot_decision_boundaries(X_scaled, y, model_ovo, "Fronteiras de Decisão OvO")

from sklearn.datasets import make_blobs
import matplotlib.pyplot as plt

# Gerando um conjunto de dados sintético com 3 centros (times)
X, y = make_blobs(n_samples=300, centers=3, random_state=42, cluster_std=2.5)

# Visualizando os dados
plt.figure(figsize=(8, 6))
plt.scatter(X[:, 0], X[:, 1], c=y, cmap='viridis', edgecolor='k', s=50)
plt.title("Conjunto de Dados Sintético com 3 Times")
plt.xlabel("Característica 1")
plt.ylabel("Característica 2")
plt.show()
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline

# Dividindo os dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Criando o modelo OvR com um pipeline que inclui normalização e SVM
model_ovr = make_pipeline(StandardScaler(), OneVsRestClassifier(SVC(kernel='linear')))

# Treinando o modelo
model_ovr.fit(X_train, y_train)

# Função para visualizar as fronteiras de decisão
def plot_decision_boundary(X, y, model, title):
    # Definindo a grade de valores
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx, yy = np.meshgrid(np.linspace(x_min, x_max, 500), np.linspace(y_min, y_max, 500))

    # Fazendo previsões para cada ponto na grade
    Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)

    # Plotando as fronteiras de decisão
    plt.contourf(xx, yy, Z, alpha=0.5, cmap='viridis')
    plt.scatter(X[:, 0], X[:, 1], c=y, cmap='viridis', edgecolor='k')
    plt.title(title)
    plt.xlabel("Característica 1")
    plt.ylabel("Característica 2")
    plt.show()

# Visualizando as fronteiras de decisão para OvR
plot_decision_boundary(X, y, model_ovr, "Fronteiras de Decisão - OvR")
from sklearn.multiclass import OneVsOneClassifier

# Criando o modelo OvO com um pipeline que inclui normalização e SVM
model_ovo = make_pipeline(StandardScaler(), OneVsOneClassifier(SVC(kernel='linear')))

# Treinando o modelo
model_ovo.fit(X_train, y_train)

# Visualizando as fronteiras de decisão para OvO
plot_decision_boundary(X, y, model_ovo, "Fronteiras de Decisão - OvO")

frutas = np.array([
    [255, 5],
    [255, 6],
    [255, 7],
    [58, 3],
    [58, 4],
    [58, 5],
    [200, 7],
    [200, 8],
    [200, 9],
])

K_means = KMeans(n_clusters=3)
K_means.fit(frutas)

labels = K_means.labels_
print(labels)
centroids = K_means.cluster_centers_
print(centroids)

plt.scatter(frutas[:, 0], frutas[:, 1], c=labels, cmap='viridis')
plt.scatter(centroids[:, 0], centroids[:, 1], s=200, c='red', marker='x')
plt.xlabel("Cor")
plt.ylabel("Tamanho")
plt.title("K-Means Clustering")
plt.show()

#usuarios gostos por filmes, 0 para acao, 1 para romance, 2 para comedia, 3 para animação. [genero, horas assistidas]
users_taste = np.array([
    [0, 5],
    [0, 6],
    [0, 7],
    [1, 8],
    [1, 9],
    [1, 10],
    [2, 2],
    [2, 3],
    [2, 4],
    [3, 11],
    [3, 12],
    [3, 13]
])

k = KMeans(n_clusters=4)
k.fit(users_taste)
label = k.labels_
centroides = k.cluster_centers_
print(centroides)

plt.scatter(users_taste[:, 0], users_taste[:, 1], c=label, cmap='viridis')
plt.scatter(centroides[:, 0], centroides[:, 1], s=200, c='red', marker='x')
plt.xlabel("Genero")
plt.ylabel("Horas assistidas")
plt.title("K-Means Clustering")
plt.show()

iris = load_iris(as_frame=True)
x = iris.data
y = iris.target

df = sns.load_dataset('iris')

plt.figure(figsize=(10, 10))
sns.pairplot(df, hue='species', diag_kind='hist', markers='+', palette='husl')
plt.suptitle('Conjunto de Dados Iris sem Redução de Dimensionalidade', fontsize=16)
plt.show()

iris = load_iris()
x = iris.data
y = iris.target

# cria objeto PCA com 2 componentes principais
pca = PCA(n_components=2)

#aplica PCA nos dados
X_pca = pca.fit_transform(x)

plt.figure(figsize=(8, 6))
colors = ['navy', 'turquoise', 'darkorange']
lw = 2

for color, i, target_name in zip(colors, [0, 1, 2], iris.target_names):
  plt.scatter(X_pca[y == i, 0], X_pca[y == i, 1], color=color, alpha=.8, lw=lw, label=target_name)
plt.legend(loc='best', shadow=False, scatterpoints=1)
plt.title('PCA do conjunto de dados Iris')
plt.xlabel('Componente Principal 1')
plt.ylabel('Componente Principal 2')

#plotando as direções dos componentes principais
for i, (component, var) in enumerate(zip(pca.components_, pca.explained_variance_)):
  comp = component * 3 * np.sqrt(var)
  plt.arrow(0, 0, comp[0], comp[1], head_width=0.1, head_length=0.1, fc='k', ec='k')
  plt.annotate(f"PC {i+1}", (comp[0], comp[1]), ha='center', va='center')

plt.axis('equal')
plt.show()

# Carregando o conjunto de dados Iris
iris = load_iris()
X = iris.data

# Criando o objeto PCA com 2 componentes
pca = PCA(n_components=2)

# Aplicando a redução de dimensionalidade
X_reduced = pca.fit_transform(X)
# Visualizando os dados reduzidos
import matplotlib.pyplot as plt
plt.scatter(X_reduced[:, 0], X_reduced[:, 1], c=iris.target)
plt.xlabel('Componente Principal 1')
plt.ylabel('Componente Principal 2')
plt.title('Redução de Dimensionalidade com PCA')
plt.show()

# Carregando o conjunto de dados Iris
iris = load_iris()
X = iris.data
y = iris.target

# Criando o objeto PCA com 2 componentes
pca = PCA(n_components=2)

# Aplicando a redução de dimensionalidade
X_reduced = pca.fit_transform(X)
colors = ['navy', 'turquoise', 'yellow']

# Visualizando os dados reduzidos
for i in range(3):
  plt.scatter(X_reduced[y == i, 0], X_reduced[y == i, 1], color=colors[i])

plt.xlabel('Componente Principal 1')
plt.ylabel('Componente Principal 2')
plt.title('Redução de Dimensionalidade com PCA')
plt.show()

np.random.seed(42)
X_reduced = np.random.randn(150, 2)  # 150 pontos
y = np.array([0]*50 + [1]*50 + [2]*50)  # Classes

# Método 1 - cores automáticas
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.scatter(X_reduced[:, 0], X_reduced[:, 1], c=y, alpha=0.6)
plt.title("c=y (automático)")

# Método 2 - loop manual
plt.subplot(1, 2, 2)
colors = ['red', 'blue', 'green']
for i in range(3):
    plt.scatter(X_reduced[y == i, 0], X_reduced[y == i, 1],
                color=colors[i], alpha=0.6)
plt.title("Loop manual")

plt.show()

# Carregar dados de exemplo
data = load_iris()
X = data.data
feature_names = data.feature_names

# Escalonar os dados (prática recomendada para PCA)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Aplicar PCA (ex: reduzindo para 2 componentes)
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

# Criar um DataFrame para visualizar os loadings (pesos)
# As linhas são os componentes principais e as colunas são as features originais
loadings = pd.DataFrame(pca.components_, columns=feature_names, index=['PC1', 'PC2'])

print("Pesos (Loadings) das features originais nos Componentes Principais:")
print(loadings)

# Visualizar a variância explicada por cada componente
print("\nVariância explicada por cada componente:")
print(pca.explained_variance_ratio_)

print("######")
# Vamos criar DataFrames para comparar
df_original = pd.DataFrame(X_scaled, columns=feature_names)
df_pca = pd.DataFrame(X_pca, columns=['PC1', 'PC2'])

print("\n=== COMPARAÇÃO ===")
print("DataFrame original (primeiras 3 linhas):")
print(df_original.head(3))

print("\nDataFrame após PCA (primeiras 3 linhas):")
print(df_pca.head(3))

print("\nColunas originais:", list(df_original.columns))
print("Colunas após PCA:", list(df_pca.columns))

iris = load_iris()
x = iris.data
y = iris.target

pca = PCA(n_components=2)

x_pca = pca.fit_transform(x)

plt.scatter(x_pca[:, 0], x_pca[:, 1], c=y)
plt.xlabel('Componente Principal 1')
plt.ylabel('Componente Principal 2')
plt.title('Redução de Dimensionalidade com PCA')
plt.show()

#Garanti resultados consistente toda vez que rodar o programa
np.random.seed(42)
#np.random.rand(40, 1) => Cria um array bimendicional com uma coluna e 40 linhas
X = np.sort(5 * np.random.rand(40, 1), axis=0)
#np.sin() calcula o valor do seno trigonométrico para cada elemento de um array
y = np.sin(X).ravel()
y[::5] += 3 * (0.5 - np.random.rand(8))

degree = 15
model = make_pipeline(PolynomialFeatures(degree), LinearRegression())

model.fit(X, y)

#Plotando os dados e o modelo
X_plot = np.linspace(0, 5, 100)[:, np.newaxis]
y_plot = model.predict(X_plot)

plt.figure(figsize=(8, 6))
plt.scatter(X, y, color='red', label='Dados de Treinamento')
plt.plot(X_plot, y_plot, color='blue', linewidth=2, label='Modelo com Overfitting')
plt.xlabel('X')
plt.ylabel('y')
plt.legend()
plt.title('Regressão Linear com Overfitting')
plt.show()

data = np.loadtxt('cal_housing.data', delimiter=',')

# X = data[:, :-1] => Features/entradas: todas as linhas, todas as colunas EXCETO a última
# y = data[:, -1]=> Target/saída: todas as linhas, APENAS a última coluna
X, y = data[:, :-1], data[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Cria modelos de regressão com diferentes valores de alpha
alphas = [0.1, 1.0, 10.0]
ridge_models = [Ridge(alpha=a) for a in alphas]
linear_model = LinearRegression()

#Calculando os scores de validadação de cada modelo
cv_scores_rigde = [cross_val_score(model, X_train, y_train, cv=5).mean() for model in ridge_models]
cv_scores_linear = cross_val_score(linear_model, X_train, y_train, cv=5).mean()

#Treinando os modelos
for model in ridge_models:
  model.fit(X_train, y_train)
linear_model.fit(X_train, y_train)
#Calculando os scores de treinamento e teste para cada modelo
train_scores_ridge = [model.score(X_train, y_train) for model in ridge_models]
test_scores_ridge = [model.score(X_test, y_test) for model in ridge_models]
train_score_linear = linear_model.score(X_train, y_train)
test_score_linear = linear_model.score(X_test, y_test)

# Imprimindo os scores de treinamento e teste
print("Scores de Treinamento (Ridge):", train_scores_ridge)
print("Scores de Teste (Ridge):", test_scores_ridge)
print("Score de Treinamento (Linear):", train_score_linear)
print("Score de Teste (Linear):", test_score_linear)

#Fazendo previsões nos conjuntos de teste
y_test_pred_ridge = [model.predict(X_test) for model in ridge_models]
y_test_pred_linear = linear_model.predict(X_test)

#Plotando os resultados
plt.figure(figsize=(12, 6))

#Gráfico dos scores de validação cruzada
plt.subplot(1, 2, 1)
plt.plot(alphas, cv_scores_ridge, marker='o', label='Ridge')
plt.axhline(cv_scores_linear, color='red', linestyle='--', label='Linear')
plt.xscale('log')
plt.xlabel('Alpha')
plt.ylabel('Score de Validação Cruzada')
plt.title('Scores de Validação Cruzada')
plt.legend()
plt.grid(True)

#Gráfico das previsões no conjunto de teste
plt.subplot(1, 2, 2)
for i, alpha in enumerate(alphas):
  plt.scatter(y_test, y_test_pred_ridge[i], alpha=0.5, label=f'Ridge (alpha={alpha})')
plt.scatter(y_test, y_test_pred_linear, color='red', alpha=0.5, label='Linear')
#plt.plot([0, 5], [0, 5], color='black', linestyle='--')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()],
         color='black', linestyle='--', linewidth=2, label='Predição Perfeita')
plt.xlabel('Valores Reais')
plt.ylabel('Previsões')
plt.title('Previsões no Conjunto de Teste')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()


#Plot individual

# plt.scatter(y_test, y_test_pred_ridge[0], alpha=0.5, label=f'Ridge (alpha={0.1})', c='red')
# plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()],
#          color='black', linestyle='--', linewidth=2, label='Predição Perfeita')
# plt.xlabel('Valores Reais')
# plt.ylabel('Previsões')
# plt.title('Previsões no Conjunto de Teste')
# plt.legend()
# plt.grid(True)
# plt.tight_layout()
# plt.show()

# plt.scatter(y_test, y_test_pred_ridge[1], alpha=0.5, label=f'Ridge (alpha={1.0})', c='green')
# plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()],
#          color='black', linestyle='--', linewidth=2, label='Predição Perfeita')
# plt.xlabel('Valores Reais')
# plt.ylabel('Previsões')
# plt.title('Previsões no Conjunto de Teste')
# plt.legend()
# plt.grid(True)
# plt.tight_layout()
# plt.show()

# plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()],
#          color='black', linestyle='--', linewidth=2, label='Predição Perfeita')
# plt.scatter(y_test, y_test_pred_ridge[2], alpha=0.5, label=f'Ridge (alpha={10.0})', c='blue')
# plt.xlabel('Valores Reais')
# plt.ylabel('Previsões')
# plt.title('Previsões no Conjunto de Teste')
# plt.legend()
# plt.grid(True)
# plt.tight_layout()
# plt.show()

np.random.seed(42)
X = np.sort(5 * np.random.rand(40, 1), axis=0)
y = np.sin(X).ravel()
y[::5] += 3 * (0.5 - np.random.rand(8))

model = LinearRegression()
model.fit(X, y)

X_plot = np.linspace(0, 5, 100)[:, np.newaxis]
y_plot = model.predict(X_plot)

plt.figure(figsize=(8, 6))
plt.scatter(X, y, color='red', label='Dados de Treinamento')
plt.plot(X_plot, y_plot, color='green', linewidth=2, label='Modelo com Overfitting')
plt.xlabel('X')
plt.ylabel('y')
plt.legend()
plt.title('Exemplo de Underfitting')
plt.show()

np.random.seed(42)
X = np.sort(5 * np.random.rand(40, 1), axis=0)
y = np.sin(X).ravel()
y[::5] += 3 * (0.5 - np.random.rand(8))

#Criando e ajustando o modelo de regressão polinomial com regularização
poly_features = PolynomialFeatures(degree=4, include_bias=False)
X_poly = poly_features.fit_transform(X)

model_poly_reg = Ridge(alpha=0.1)

#Avaliando o modelo usando validação cruzada
cv_scores = cross_val_score(model_poly_reg, X_poly, y, cv=5)
print("Scores da validação cruzada:", cv_scores)
print("Média dos scores da validação cruzada:", np.mean(cv_scores))

#Ajustando o modelo aos dados
model_poly_reg.fit(X_poly, y)

#Plotando os dados, o modelo original e o modelo polinomial com regularização
X_plot = np.linspace(0, 5, 100)[:, np.newaxis]
X_plot_poly = poly_features.transform(X_plot)
y_plot_poly_reg = model_poly_reg.predict(X_plot_poly)

plt.figure(figsize=(8, 6))
plt.scatter(X, y, color='red', label='Dados de Treinamento')
plt.plot(X_plot, y_plot_poly_reg, color='blue', linewidth=2, label='Modelo Polinomial com Regularização')
plt.xlabel('X')
plt.ylabel('y')
plt.legend()
plt.title('Regressão Polinomial com Regularização')
plt.show()

iris = load_iris()
x = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

svm = SVC()

#Defnindo os hiperparametros a serem testados
param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf'],
    'gamma': [0.1, 1, 10]
}

grid_search = GridSearchCV(svm, param_grid, cv=5)
grid_search.fit(X_train, y_train)

best_params  = grid_search.best_params_
print("best_params: ", best_params )

best_svm = SVC(**best_params)
best_svm.fit(X_train, y_train)

y_pred = best_svm.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("accuracy: ", accuracy)

#random search
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Step 1: Define The Parameter Space Or Distribution

# Define hyperparameter distributions
param_dist = {
    'n_estimators': [int(x) for x in np.linspace(start=200, stop=2000, num=10)],  # Number of trees
    'max_features': ['auto', 'sqrt'],  # Number of features to consider for best split
    'max_depth': [int(x) for x in np.linspace(10, 110, num=11)],  # Maximum depth of the trees
    'min_samples_split': [2, 5, 10],  # Minimum samples required to split a node
    'min_samples_leaf': [1, 2, 4],  # Minimum samples required at each leaf node
    'bootstrap': [True, False]  # Whether bootstrap samples are used when building trees
}

# Step 2: Prime The Random Search Object

from sklearn.model_selection import RandomizedSearchCV

# Create a Random Forest Classifier
rf_classifier = RandomForestClassifier()

# Create the RandomizedSearchCV object
random_search = RandomizedSearchCV(
    estimator=rf_classifier,
    param_distributions=param_dist,
    n_iter=100,  # Number of parameter settings that are sampled
    cv=5,  # Number of cross-validation folds
    verbose=2,
    scoring="accuracy",
    random_state=42,
    n_jobs=-1  # Use all available processors
)

# Step 3: Fit The Data & Extract The Results

data = load_iris()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Fit the RandomizedSearchCV instance
random_search.fit(X_train, y_train)

# Retrieve the best parameters found by RandomizedSearchCV
best_params = random_search.best_params_
print("Best Parameters:", best_params)

# Evaluate the model with best parameters on the test set
best_estimator = random_search.best_estimator_
test_accuracy = best_estimator.score(X_test, y_test)
print("Test Accuracy with Best Parameters:", test_accuracy)

